title: 少安事务所
description: Read, Record, and Review.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

#baseurl: "/blog"
#url: http://localhost:4000

#timezone: Asia/Shanghai
#avatar: https://avatars0.githubusercontent.com/u/17957066?s=400&u=b39871eafed2e90aecd42910d9cd8bc642618177&v=4
#avatar: assets/img/1.jpg
avatar: assets/img/yoga_and_linux.png
author: ShawnYan
email: shawn2016@aliyun.com

github:
  is_user_page: true
  owner_url: http://github.com/shawn0915
  owner_name: Shawn Yan
  repository_name: shawn0915.github.io

# social links
github_username: shawn0915

# inject into Gemfile with "gem 'jekyll-paginate'"
# https://jekyllrb.com/docs/pagination/#enable-pagination
# Plugin jekyll-paginate-v2 is not supported by GitHub Pages.
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "/:num"
